#include <stdio.h>
#include <stdlib.h>

#define FDS_IMPL
#include "fds__cpp.h"

// Підключаємо реалізації (передбачається, що fds_ext_string також має свій _IMPLEMENTATION макрос, якщо це STB)
#define FDS_EMITTER_IMPLEMENTATION
#include "fds_emitter.h"

int main() {
    // 1. Ініціалізація
    SB sb = {0};
    // sb_init(&sb); // або інша функція ініціалізації з вашої ліби

    FdsEmitter e;
    fds_emitter_init(&e, &sb);
    
    // Якщо хочемо перевірити вимкнення дебагу в рантаймі:
    // fds_emitter_enable_debug(&e, false);

    // 2. Тестування генерації
    fds_emitter_comment(&e, "Test File Generated by FDS Emitter");
    fds_emitter_newline(&e);

    FDS_EMITTER_BLOCK(&e, "int calculate_sum(int a, int b) {", "}") {
        fds_emitter_label(&e, ".entry");
        
        fds_emitter_line(&e, "int result = 0;");
        
        FDS_EMITTER_BLOCK(&e, "if (a > 0) {", "}") {
            // Тест часткового запису (write)
            fds_emitter_write(&e, "result = ");
            fds_emitter_write(&e, "a + b;");
            fds_emitter_newline(&e); // Закриваємо рядок
        }
        
        fds_emitter_line(&e, "return result;");
    }

    // 3. Вивід результату
    // Припустимо, що у sb є доступ до буфера та його розміру:
    printf("--- GENERATED CODE ---\n");
    printf("%s\n", sb.items); // або printf("%.*s", (int)sb.length, sb.data);
    printf("----------------------\n");

    // Очищення (залежить від реалізації SB)
    // fds_sb_free(&sb);

    return 0;
}